title: Łódzkie Filmowy Region
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://filmowelodzkie.pl"
permalink: /:categories/:title/
excerpt_separator: <wiecej>
collections:
  filmy:
    output: true
    permalink: /filmy/:path/
  lokacje:
    output: true
    permalink: /lokacje/:path/
defaults:
  - scope:
      path: ""
    values:
      layout: "strona"
  - scope:
      path: ""
      type: "filmy"
    values:
      layout: "film"
  - scope:
      path: ""
      type: "lokacje"
    values:
      layout: "lokacja"
  - scope:
      type: "posts"
    values:
      category: "aktualnosci"